import {
  Baby,
  BookOpen,
  Car,
  Clapperboard,
  Coffee,
  Dumbbell,
  Ellipsis,
  Fuel,
  Gamepad2,
  Gift,
  GraduationCap,
  HeartPulse,
  House,
  Landmark,
  Laptop,
  Lightbulb,
  type LucideIcon,
  Music,
  PawPrint,
  PiggyBank,
  Pill,
  Plane,
  Receipt,
  Scissors,
  Shirt,
  ShoppingBag,
  ShoppingBasket,
  Smartphone,
  Sparkles,
  TrainFront,
  Utensils,
  Wifi,
  Wrench,
} from "lucide-react";

/** Curated icon set for categories. Keys are persisted; never rename a key. */
export const CATEGORY_ICONS = {
  utensils: Utensils,
  coffee: Coffee,
  basket: ShoppingBasket,
  car: Car,
  train: TrainFront,
  fuel: Fuel,
  bag: ShoppingBag,
  shirt: Shirt,
  receipt: Receipt,
  lightbulb: Lightbulb,
  wifi: Wifi,
  phone: Smartphone,
  house: House,
  wrench: Wrench,
  health: HeartPulse,
  pill: Pill,
  dumbbell: Dumbbell,
  scissors: Scissors,
  sparkles: Sparkles,
  film: Clapperboard,
  music: Music,
  game: Gamepad2,
  plane: Plane,
  education: GraduationCap,
  book: BookOpen,
  gift: Gift,
  baby: Baby,
  pet: PawPrint,
  bank: Landmark,
  piggy: PiggyBank,
  laptop: Laptop,
  other: Ellipsis,
} satisfies Record<string, LucideIcon>;

export type CategoryIconKey = keyof typeof CATEGORY_ICONS;

export const CATEGORY_ICON_KEYS = Object.keys(CATEGORY_ICONS) as [
  CategoryIconKey,
  ...CategoryIconKey[],
];
